---
- name: Download Kibana's rpm
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kb_version }}-x86_64.rpm"
    dest: "/tmp/kibana-{{ elk_stack_version }}-x86_64.rpm"
  register: download_kb
  until: download_kb is succeeded
