---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure kibana installed
      package:
        name: "kibana"
        state: present
    - name: Ensure kibana started
      become: true
      command: /etc/init.d/kibana status
      register: status_result
      changed_when: status_result.stdout == "kibana is not running"
      ignore_errors: yes
    - name: Start kibana
      become: true
      command: /etc/init.d/kibana start
      register: start_result
      until: start_result is succeeded
      changed_when: status_result.stdout == "kibana is not running"